version: '3'

services:
  coder-server:
    image: code_esp_idf
    container_name: code_esp_bt32
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 192.168.2.11
    dns:
      - 192.168.2.2
    ports:
      - "3232:8080"
      - "3233:9000"
    volumes:
      - code_esp_bt32:/home/coder/project
      - code_esp_bt32_config:/home/coder/.config
    environment:
      - PASSWORD=3956
      - DOCKER_USER=${USER}
      - IDF_PATH=/opt/esp/idf
      - IDF_TOOLS_PATH=/opt/esp
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"

volumes:
  code_esp_bt32:
  code_esp_bt32_config:

networks:
  pihole_net:
    external: true
