version: '3'

services:
  coder-server:
    image: coder_esp32  # Reemplaza con el nombre de tu imagen
    container_name: coder32-esp-idf
    restart: unless-stopped
    ports:
      - "9050:8080"  # Exponer code-server en el puerto 9010
    volumes:
      - coder32_data:/home/coder/project  # Montar los datos del proyecto
      - coder32_config:/home/coder/.config  # Montar la configuración de code-server
    environment:
      - PASSWORD=pwd  # Establece la contraseña de code-server
      - DOCKER_USER=${USER}  # Establece el usuario de Docker
      - IDF_PATH=/opt/esp/idf  # Variables de entorno de ESP-IDF
      - IDF_TOOLS_PATH=/opt/esp
    tty: true  # Mantener el contenedor interactivo
    stdin_open: true  # Habilitar stdin para sesiones interactivas
    user: "${UID}:${GID}"

volumes:
  coder32_data:
  coder32_config: